### ISSUE TITLE
Github groups

### ISSUE THREAD

**Issue by posix4e** [planetlabs/kubehook#40]
We'd like to move completely off of dex to kubehook but our current issue is groups. How do we map groups in our github to an acl mapping kubernetes. In our case, we have a namespace we wanna restrict to members in a github group. Love the product!

**Comment by jacobstr** [comment]
Some notes from our setup, which might provide some insight:

```
Kubehook does not authenticate users. Instead it assumes it is running behind an
authenticating reverse proxy. Kubehook generates a JWT for the user specified
via a configurable HTTP header, in our case `X-SAML-Email`. This JWT also
includes a user's LDAP groups, which are passed via the `X-SAML-Groups` header.
```

We control that with the --user-header and [--group-header](https://github.com/planetlabs/kubehook/blob/master/cmd/kubehook/kubehook.go#L121) flags, which are also bound to envvars:

```
KUBEHOOK_USER_HEADER=X-SAML-Email
KUBEHOOK_GROUP_HEADER=X-Saml-Groups
```

**Comment by jacobstr** [comment]
I don't believe there is a facility to e.g. mapping group names (say stripping / injecting a prefix). If patterned off of what we're doing, you might do something akin to:

- Forward to Github for auth.
- You've now got an OIDC token (I presume - haven't integrated with their auth setup myself).
- A custom backend proxy that you write validates your OIDC token, implements your group matching / filtering logic. This proxy sits in front of your kubetoken instance.

**Comment by posix4e** [comment]
Does that mean I should run 3 kubehook endpoints which generate kubecredentials with different acls and have nginx send to the correct kubehook? How do I control the acls that kubehook runs.

**Comment by posix4e** [comment]
I shouldn't even need a proxy. I can just run 3 different ingresses for the 3 different groups I have. However, how do I limit the kubectl credentials that kubehook is printing in each different configuration?
